version: '3.7'

services:
  data-catalog:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - '.:/usr/src/app'
    ports:
      - 8083:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@catalog-db:5432/catalog_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@catalog-db:5432/catalog_test
      - MESSAGE=no_etcd_working
    depends_on:
      - catalog-db
      - etcd
    networks:
      - backend 
  catalog-db:
    build:
      context: ./app/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend
  etcd:
   image: quay.io/coreos/etcd:latest
   ports:
     - "2379:2379"
   networks:
      - backend   
   command: >-
     /usr/local/bin/etcd
     -name node1
     -advertise-client-urls http://etcd:2379
     -listen-client-urls http://0.0.0.0:2379
     -initial-advertise-peer-urls http://etcd:2380
     -listen-peer-urls http://0.0.0.0:2380
     -initial-cluster node1=http://etcd:2380
     -cors="*"
networks:
  backend:
    external: true
  
