# 
swagger: "2.0"

info:
  title: "Data catalog microservice API"
  version: "1.0"
consumes:
  - "application/json"
produces:
  - "application/json"


basePath: "/api/v1.0"

# defines the section of the configuration containing all of the API REST endpoints
paths:
  #  defines one path of your URL endpoint.
  /datasets:
    # defines the HTTP method this URL endpoint will respond to. Together with the previous definitions, this creates the GET /api/v1.0/datasets URL endpoint.
    get:
      operationId: "api.datasets.datasets.read_all"
      tags:
        - "Datasets"
      responses:
        '200':
          description: 'Fetch a list of items'
          schema:
            $ref: '#/definitions/Dataset'

  #   post:
  #     operationId: "api.datasets.datasets.create"
  /datasets/{dataset_id}:
    get:
      operationId: "api.datasets.datasets.read_one"
      tags:
        - "Datasets"
      summary: Read dataset info from database metadata
      description: Read dataset info from database metadata
      parameters:
        - name: dataset_id
          in: path
          description: ID of the dataset to get from the database metadata
          type: integer
          required: True
      responses:
        200:
          description: Successfully read dataset info from database metadata
          schema:
            $ref: '#/definitions/Dataset'
  #   put:
  #     operationId: "api.datasets.datasets.update"
  #     tags:
  #       - "Datasets"
  #     summary: Update a dataset info from the database
  #     description: Update a dataset info in the database
  #     parameters:
  #       - name: id
  #         in: path
  #         description: ID of the dataset to update in the database
  #         type: integer
  #         required: True
  #       - name: dataset_info
  #         in: body
  #         schema:
  #           type: object
  #           properties:
  #             fname:
  #               type: string
  #             lname:
  #               type: string
  #     responses:
  #       200:
  #         description: Successfully updated person in people list

  #   delete:
  #     operationId: "api.datasets.datasets.delete"
  #     tags:
  #       - "Datasets"
  #     summary: Delete a dataset from the database
  #     description: Delete a dataset
  #     parameters:
  #       - name: id
  #         in: path
  #         type: integer
  #         required: True
  #     responses:
  #       200:
  #         description: Successfully deleted a dataset from datasets

definitions:
  Dataset:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name: { type: string }
