apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-catalog-deployment
  labels:
    app: data-catalog
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: data-catalog
  template:
    metadata:
      labels:
        app: data-catalog
    spec:
      containers: 
      - image: leon11sj/data-catalog-microservice:version-1.0.0-5.1
        name: data-catalog
        command: ["gunicorn"]
        args: ["--bind", "0.0.0.0:5000", "manage:app"]
        env:
          - name: FLASK_ENV
            value: "production"
          - name: APP_SETTINGS
            value: "app.config.ProductionConfig"
          - name: FLASK_APP
            value: app/__init__.py
          - name: SQL_HOST
            value: "10.86.32.3"
          - name: SQL_PORT  
            value: "5432"
          - name: DATABASE
            value: postgres
          - name: POSTGRES_DB
            value: catalog_prod
          - name: CONFIG_ETCD_HOST_IP
            value: etcd
          - name: CONFIG_ETCD_HOST_PORT
            value: "2379"
          - name: MESSAGE
            value: "no_etcd_working"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: catalog-db-uri
                key: DATABASE_URL
        ports:
        - containerPort: 5000
          name: server
          protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: data-catalog
spec:
  type: ClusterIP
  ports:
  - port: 8083
    protocol: TCP
    targetPort: server
  selector:
    app: data-catalog
